CREATE TABLE `label_settings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`label_name` text DEFAULT 'Varsayılan Etiket' NOT NULL,
	`label_type` text DEFAULT 'ticket' NOT NULL,
	`width` integer DEFAULT 58 NOT NULL,
	`height` integer DEFAULT 30 NOT NULL,
	`header_text` text,
	`header_font_size` integer DEFAULT 12 NOT NULL,
	`footer_text` text,
	`footer_font_size` integer DEFAULT 10 NOT NULL,
	`queue_number_font_size` integer DEFAULT 24 NOT NULL,
	`bank_name_font_size` integer DEFAULT 12 NOT NULL,
	`datetime_font_size` integer DEFAULT 9 NOT NULL,
	`show_qr_code` integer DEFAULT false NOT NULL,
	`show_barcode` integer DEFAULT false NOT NULL,
	`show_datetime` integer DEFAULT true NOT NULL,
	`show_bank_info` integer DEFAULT true NOT NULL,
	`show_queue_position` integer DEFAULT true NOT NULL,
	`show_waiting_time` integer DEFAULT false NOT NULL,
	`background_color` text DEFAULT 'white' NOT NULL,
	`text_color` text DEFAULT 'black' NOT NULL,
	`border_style` text DEFAULT 'solid' NOT NULL,
	`border_width` integer DEFAULT 1 NOT NULL,
	`logo_url` text,
	`logo_width` integer DEFAULT 40 NOT NULL,
	`logo_height` integer DEFAULT 20 NOT NULL,
	`custom_message_1` text,
	`custom_message_2` text,
	`custom_message_3` text,
	`is_active` integer DEFAULT true NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
